on:
  push:
    branches-ignore: [v2.x/staging, v2.x/master]

  pull_request:
    branches: [v2.x/staging, v2.x/master]

jobs:
  build:

    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: v2.x/staging
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    